menu:
  en:
    - {name: 'One', folder: 'en', file: 'facts.html'}
    - {name: 'Two', folder: 'en', file: 'facts.html'}
    - {name: 'Three', folder: 'en', file: 'facts.html'}
  fr:
    - {name: 'Un', folder: 'fr', file: 'facts.html'}
    - {name: 'Deux', folder: 'fr', file: 'facts.html'}
    - {name: 'Trois', folder: 'fr', file: 'facts.html'}
