menu:
  en:
    - {name: 'about', folder: 'en', file: 'facts.html'}
    - {name: 'guide', folder: 'en', file: 'facts.html'}
    - {name: 'toolbox', folder: 'en', file: 'facts.html'}
    - {name: 'connections', folder: 'en', file: 'facts.html'}
    - {name: 'credits', folder: 'en', file: 'facts.html'}
  fr:
    - {name: 'à propos', folder: 'fr', file: 'facts.html'}
    - {name: 'guide', folder: 'fr', file: 'facts.html'}
    - {name: 'boîte à outils', folder: 'fr', file: 'facts.html'}
    - {name: 'liens', folder: 'fr', file: 'facts.html'}
    - {name: 'crédits', folder: 'fr', file: 'facts.html'}
